export const ERROR_CODES = {
  INVALID_PARAMETERS: 'INVALID_PARAMETERS',
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  RESTAURANT_ALREADY_EXISTS: 'RESTAURANT_ALREADY_EXISTS',
  UNSUPPORTED_LANGUAGE: 'UNSUPPORTED_LANGUAGE',
};
